name: sq_lite_application1
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.4.1
  path: ^1.8.3



dev_dependencies:

 
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

 
  uses-material-design: true

